<?php
$product = $block->getProduct();;
?>
<div class="healthlab__body">
    <div id="product-popup"></div>
    <div class="healthlab__product-detail container-content">
        <div class="insight-breadcrumb" style="margin-top:50px;">
            <?php $breabcrumbs = $block->getBreadcrumb() ?>
            <?php foreach($breabcrumbs  as $breabcrumb): ?>
                <?php if($breabcrumb != null): ?>
                    <a href="<?= $block->escapeUrl($breabcrumb["url"]) ?>"><?= $breabcrumb["title"] ?></a>
                    <span>|</span>
                <?php endif; ?>
            <?php endforeach; ?>
            <a href="javascript:void(0)"><?= $product->getName() ?></a>
        </div>
        <?= $this->getChildHtml('healthlab_header_product'); ?>
        <div class="product__content-bottom">
            <?= $this->getChildHtml('healthlab_list_categories_product'); ?>
            <?= $this->getChildHtml('healthlab_description_product'); ?>
            <?php
                $content = $block->getChildBlock('healthlab_related_product');
                if ($content) {
                    $content->setData('detail_url', 'ingredient/detail/product');
                    echo $content->toHtml();
                }
            ?>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
    	"*": {
            "Annam_ProductCatalog/js/carousel": {},
    		"Annam_HealthLab/js/product-wishlist": {
    			"url": "<?= $block->getAddToWishlistUrl(); ?>",
    			"isLoggedInUrl" : "<?= $block->getIsLoggedIntUrl(); ?>"
    		}
    	}
    }
</script>
