<?php

/**
 * @author ICT
 * @copyright Copyright (c) 2024 Juni.com
 * @package A Magento 2 Invoice SYNC To LKG System Module.
 */

namespace Lkg\InvoiceSync\Helper;

class ShortCountryCode
{
    /**
     * All Country Codes
     *
     * @param string $countryCode The ISO 3166-1 alpha-2 country code.
     * @return string|null The corresponding country value or null if the country code is not found.
     */
    public function getCountryValue($countryCode)
    {
        // Define the key-value array
        $keyValueArray = [
                'AT' => 'A',
                'AF' => 'AFG',
                'AG' => 'AG',
                'AI' => 'AGU',
                'AL' => 'AL',
                'AD' => 'AND',
                'AO' => 'ANG',
                'AM' => 'ARM',
                'AW' => 'ARU',
                'AC' => 'ASC',
                'AZ' => 'ASE',
                'AS' => 'ASM',
                'AQ' => 'ATA',
                'TF' => 'ATF',
                'AU' => 'AUS',
                'AX' => 'AX',
                'BE' => 'B',
                'BD' => 'BD',
                'BB' => 'BDS',
                'BJ' => 'BEN',
                'BM' => 'BER',
                'BQ' => 'BES',
                'BF' => 'BF',
                'BG' => 'BG',
                'BT' => 'BHT',
                'BA' => 'BIH',
                'BL' => 'BLM',
                'BY' => 'BLR',
                'BO' => 'BOL',
                'BR' => 'BR',
                'VG' => 'BRJ',
                'BH' => 'BRN',
                'BN' => 'BRU',
                'BS' => 'BS',
                'MM' => 'BUR',
                'BV' => 'BVT',
                'BZ' => 'BZ',
                'CU' => 'C',
                'CM' => 'CAM',
                'CC' => 'CCK',
                'CA' => 'CDN',
                'CD' => 'CGO',
                'CH' => 'CH',
                'CI' => 'CI',
                'LK' => 'CL',
                'CN' => 'CN',
                'CO' => 'CO',
                'CK' => 'COK',
                'KM' => 'COM',
                'CR' => 'CR',
                'CW' => 'CUW',
                'CV' => 'CV',
                'CX' => 'CXE',
                'CY' => 'CY',
                'CZ' => 'CZ',
                'DE' => 'D',
                'DJ' => 'DJI',
                'DK' => 'DK',
                'DO' => 'DOM',
                'DZ' => 'DZ',
                'ES' => 'E',
                'KE' => 'EAK',
                'TZ' => 'EAT',
                'UG' => 'EAU',
                'EC' => 'EC',
                'IC' => 'ECA',
                'EE' => 'EE',
                'ER' => 'ERI',
                'SV' => 'ES',
                'EG' => 'ET',
                'ET' => 'ETH',
                'FR' => 'F',
                'GF' => 'FGU',
                'FI' => 'FIN',
                'FJ' => 'FJI',
                'LI' => 'FL',
                'FK' => 'FLK',
                'PF' => 'FPO',
                'FO' => 'FR',
                'FM' => 'FSM',
                'GA' => 'G',
                'GB' => 'GB',
                'GG' => 'GBG',
                'JE' => 'GBJ',
                'IM' => 'GBM',
                'GI' => 'GBZ',
                'GT' => 'GCA',
                'GE' => 'GEO',
                'GH' => 'GH',
                'GQ' => 'GQ',
                'GR' => 'GR',
                'GP' => 'GUA',
                'GW' => 'GUB',
                'GU' => 'GUM',
                'GY' => 'GUY',
                'HU' => 'H',
                'HN' => 'HCA',
                'HK' => 'HK',
                'HM' => 'HMD',
                'HR' => 'HR',
                'IT' => 'I',
                'IL' => 'IL',
                'IN' => 'IND',
                'IO' => 'IOT',
                'IR' => 'IR',
                'IE' => 'IRL',
                'IQ' => 'IRQ',
                'IS' => 'IS',
                'JP' => 'J',
                'JM' => 'JA',
                'JO' => 'JOR',
                'KH' => 'K',
                'KY' => 'KAI',
                'KZ' => 'KAS',
                'KG' => 'KGZ',
                'KI' => 'KIR',
                'GL' => 'KN',
                'KW' => 'KWT',
                'LU' => 'L',
                'LA' => 'LAO',
                'LY' => 'LAR',
                'LR' => 'LB',
                'LT' => 'LIT',
                'LS' => 'LS',
                'LV' => 'LV',
                'MT' => 'M',
                'MA' => 'MA',
                'MO' => 'MAC',
                'MF' => 'MAF',
                'MK' => 'MAK',
                'MY' => 'MAL',
                'MC' => 'MC',
                'MX' => 'MEX',
                'MQ' => 'MH',
                'MH' => 'MHL',
                'ME' => 'MNE',
                'MN' => 'MNG',
                'MP' => 'MNP',
                'MZ' => 'MOC',
                'MD' => 'MOL',
                'MU' => 'MS',
                'MS' => 'MSE',
                'MV' => 'MV',
                'MW' => 'MW',
                'NO' => 'N',
                'AN' => 'NA',
                'NA' => 'NAM',
                'NR' => 'NAU',
                'NP' => 'NEP',
                'NF' => 'NFK',
                'PG' => 'NG',
                'NI' => 'NIC',
                'NU' => 'NIU',
                'NC' => 'NKA',
                'NL' => 'NL',
                'KP' => 'NOC',
                'NZ' => 'NZ',
                'OM' => 'OM',
                'PT' => 'P',
                'PA' => 'PA',
                'PW' => 'PAL',
                'PE' => 'PE',
                'PN' => 'PIT',
                'PK' => 'PK',
                'PL' => 'PL',
                'PR' => 'PRI',
                'PY' => 'PY',
                'QA' => 'Q',
                'RU' => 'R',
                'AR' => 'RA',
                'BW' => 'RB',
                'CF' => 'RCA',
                'CG' => 'RCB',
                'CL' => 'RCH',
                'RE' => 'REU',
                'GN' => 'RG',
                'HT' => 'RH',
                'ID' => 'RI',
                'MR' => 'RIM',
                'LB' => 'RL',
                'MG' => 'RM',
                'ML' => 'RMM',
                'NE' => 'RN',
                'RO' => 'RO',
                'TW' => 'ROC',
                'KR' => 'ROK',
                'UY' => 'ROU',
                'PH' => 'RP',
                'SM' => 'RSM',
                'BI' => 'RU',
                'RW' => 'RWA',
                'SE' => 'S',
                'SA' => 'SA',
                'SB' => 'SAL',
                'KN' => 'SCN',
                'SZ' => 'SD',
                'SG' => 'SGP',
                'GS' => 'SGS',
                'SH' => 'SHE',
                'SI' => 'SI',
                'SJ' => 'SJM',
                'SK' => 'SK',
                'SR' => 'SME',
                'SN' => 'SN',
                'SO' => 'SO',
                'PM' => 'SPI',
                'XS' => 'SRB',
                'SS' => 'SSD',
                'LC' => 'STL',
                'ST' => 'STP',
                'SD' => 'SUD',
                'SX' => 'SXM',
                'SC' => 'SY',
                'SY' => 'SYR',
                'TH' => 'T',
                'TD' => 'TCH',
                'TC' => 'TCI',
                'TJ' => 'TJ',
                'TK' => 'TKL',
                'TL' => 'TL',
                'TN' => 'TN',
                'TO' => 'TO',
                'TG' => 'TOG',
                'TR' => 'TR',
                'TA' => 'TRI',
                'TT' => 'TT',
                'TM' => 'TUR',
                'TV' => 'TUV',
                'AE' => 'UAE',
                'UA' => 'UKR',
                'UM' => 'UMI',
                'US' => 'USA',
                'UZ' => 'USB',
                'VA' => 'V',
                'VU' => 'VAN',
                'VI' => 'VIR',
                'VN' => 'VN',
                'WF' => 'WAF',
                'GM' => 'WAG',
                'SL' => 'WAL',
                'NG' => 'WAN',
                'PS' => 'WB',
                'DM' => 'WD',
                'GD' => 'WG',
                'WS' => 'WS',
                'EH' => 'WSA',
                'VC' => 'WV',
                'XK' => 'XK',
                'YE' => 'Y',
                'YT' => 'YT',
                'VE' => 'YV',
                'ZM' => 'Z',
                'ZA' => 'ZA',
                'ZW' => 'ZW',
                '00' => '00'
                // Add more key-value pairs as needed
        ];
    
        // Check if the country code exists in the array as a key
        if (array_key_exists($countryCode, $keyValueArray)) {
            return $keyValueArray[$countryCode];
        } else {
            return null;
        }
    }
}
